import React,{useEffect} from 'react';
const PageWrap=({title,children}:{title:string,children:React.ReactNode})=>{
  useEffect(()=>{window.scrollTo(0,0)},[]);
  return(<div className="min-h-screen bg-slate-50">
    <div className="bg-slate-900 text-white py-16 px-4 text-center"><h1 className="text-4xl font-black">{title}</h1></div>
    <div className="max-w-3xl mx-auto px-4 py-12 space-y-6 text-slate-700 leading-relaxed">{children}</div>
  </div>);
};
export const PrivacyPolicy=()=>(<PageWrap title="Privacy Policy"><p className="text-sm text-slate-500">Last updated: March 2026</p><h2 className="text-xl font-black text-slate-900">Information We Collect</h2><p>We collect your name, phone number, email, and travel preferences when you submit an enquiry. This information is used solely to contact you about travel bookings and packages.</p><h2 className="text-xl font-black text-slate-900">How We Use Your Data</h2><p>Your details are used to respond to your travel queries, send relevant package updates, and coordinate your bookings. We do not sell or share your data with third parties.</p><h2 className="text-xl font-black text-slate-900">Cookies</h2><p>Our website uses essential cookies to function correctly. No tracking or advertising cookies are used.</p><h2 className="text-xl font-black text-slate-900">Contact</h2><p>For any data-related requests, email us at thetravelsguru@gmail.com or WhatsApp 9099965751.</p></PageWrap>);
export const CancellationPolicy=()=>(<PageWrap title="Cancellation Policy"><p>We understand plans change. Here is our cancellation policy:</p><div className="overflow-x-auto"><table className="w-full text-sm border-collapse bg-white rounded-2xl overflow-hidden shadow"><thead className="bg-slate-800 text-white"><tr><th className="p-3 text-left">Notice Period</th><th className="p-3 text-left">Refund</th></tr></thead><tbody><tr className="border-b"><td className="p-3">30+ days before travel</td><td className="p-3 text-green-600 font-bold">90% refund</td></tr><tr className="border-b bg-slate-50"><td className="p-3">15–29 days before</td><td className="p-3 text-yellow-600 font-bold">50% refund</td></tr><tr className="border-b"><td className="p-3">7–14 days before</td><td className="p-3 text-orange-600 font-bold">25% refund</td></tr><tr className="bg-slate-50"><td className="p-3">Less than 7 days</td><td className="p-3 text-red-600 font-bold">No refund</td></tr></tbody></table></div><p>In cases of natural disasters or force majeure, a full credit note valid for 12 months will be issued.</p><p>To cancel, WhatsApp us at <strong>9099965751</strong> or email <strong>thetravelsguru@gmail.com</strong>.</p></PageWrap>);
export const TravelInsurance=()=>(<PageWrap title="Travel Insurance"><div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 text-center"><span className="bg-amber-500 text-white text-xs font-black px-3 py-1 rounded-full uppercase">Coming Soon</span><h2 className="text-2xl font-black text-slate-900 mt-4">We're Setting This Up</h2><p className="text-slate-600 mt-2">We are finalising partnerships with leading travel insurance providers to offer comprehensive coverage directly through our platform. Expected launch: Q2 2026.</p><p className="text-slate-500 text-sm mt-4">In the meantime, we recommend purchasing travel insurance independently. Contact us for guidance: <strong>9099965751</strong></p></div></PageWrap>);
export const TermsOfService=()=>(<PageWrap title="Terms of Service"><p className="text-sm text-slate-500">Effective: March 2026</p><h2 className="text-xl font-black text-slate-900">Bookings</h2><p>All bookings are confirmed only after receipt of the required advance payment. Verbal commitments do not constitute a confirmed booking.</p><h2 className="text-xl font-black text-slate-900">Payments</h2><p>A minimum 30% advance is required to confirm your booking. The balance must be cleared 7 days before the travel date.</p><h2 className="text-xl font-black text-slate-900">Liability</h2><p>The Travel's Guru acts as a travel coordinator. We are not liable for delays, cancellations, or changes caused by airlines, hotels, or natural events beyond our control.</p><h2 className="text-xl font-black text-slate-900">Disputes</h2><p>Any disputes shall be resolved under the jurisdiction of Surat, Gujarat courts.</p></PageWrap>);
